# Generated by Django 4.1.4 on 2022-12-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=75)),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('slug_name', models.SlugField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('subtitle', models.CharField(blank=True, default='', max_length=35)),
                ('start_date', models.DateField(default=True, null=True)),
                ('finish_date', models.DateField(default=True, null=True)),
                ('upload', models.FileField(upload_to='uploads/files/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_details', to='section.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionDetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=300)),
                ('icon', models.ImageField(upload_to='uploads/icons/')),
                ('section_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_detail_items', to='section.sectiondetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
