# Generated by Django 4.1.4 on 2022-12-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectiondetail',
            old_name='upload',
            new_name='file',
        ),
    ]
