# Generated by Django 4.1.4 on 2023-01-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_rename_upload_sectiondetail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondetail',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/files/'),
        ),
        migrations.AlterField(
            model_name='sectiondetailitem',
            name='icon',
            field=models.ImageField(null=True, upload_to='uploads/icons/'),
        ),
    ]
